engines:
  bandit:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  pylint:
    enabled: true
    channel: "beta"
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/**/*
- db/**/*
- test/**/*
- docs/**/*
- doc_src/**/*